var EDGES = [
  {"from": "r1", "to": "r18", "rel": "Single-sensor limits"},
  {"from": "r1", "to": "r20", "rel": "Single-sensor limits"},
  {"from": "r18", "to": "r20", "rel": "Single-sensor limits"},
  {"from": "r2", "to": "r17", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r18", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r18", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r18", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r19", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r3", "to": "r21", "rel": "Adverse-weather perception"},
  {"from": "r3", "to": "r22", "rel": "Adverse-weather perception"},
  {"from": "r21", "to": "r22", "rel": "Adverse-weather perception"},
  {"from": "r1", "to": "r2", "rel": "GNSS/LiDAR failure modes"},
  {"from": "r2", "to": "r23", "rel": "HD-map localization"},
  {"from": "r2", "to": "r24", "rel": "HD-map localization"},
  {"from": "r2", "to": "r25", "rel": "HD-map localization"},
  {"from": "r23", "to": "r24", "rel": "HD-map localization"},
  {"from": "r23", "to": "r25", "rel": "HD-map localization"},
  {"from": "r24", "to": "r25", "rel": "HD-map localization"},
  {"from": "r1", "to": "r4", "rel": "Energy & terrain routing"},
  {"from": "r1", "to": "r26", "rel": "Energy & terrain routing"},
  {"from": "r1", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r4", "to": "r26", "rel": "Energy & terrain routing"},
  {"from": "r4", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r26", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r5", "to": "r16", "rel": "On-demand vs fixed routing"},
  {"from": "r5", "to": "r30", "rel": "On-demand vs fixed routing"},
  {"from": "r5", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r16", "to": "r30", "rel": "On-demand vs fixed routing"},
  {"from": "r16", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r30", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r19", "to": "r25", "rel": "Heterogeneous data fusion"},
  {"from": "r5", "to": "r28", "rel": "On-demand dispatch"},
  {"from": "r5", "to": "r29", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r29", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r30", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r31", "rel": "On-demand dispatch"},
  {"from": "r29", "to": "r30", "rel": "On-demand dispatch"},
  {"from": "r29", "to": "r31", "rel": "On-demand dispatch"},
  {"from": "r6", "to": "r31", "rel": "ADA pick-up"},
  {"from": "r7", "to": "r37", "rel": "Digital twins"},
  {"from": "r7", "to": "r38", "rel": "Digital twins"},
  {"from": "r37", "to": "r38", "rel": "Digital twins"},
  {"from": "r8", "to": "r25", "rel": "Rural HD maps"},
  {"from": "r32", "to": "r33", "rel": "Edge computing"},
  {"from": "r44", "to": "r45", "rel": "V2X cybersecurity"},
  {"from": "r10", "to": "r35", "rel": "Cooperative perception"},
  {"from": "r34", "to": "r36", "rel": "Edge RSU handover"},
  {"from": "r40", "to": "r41", "rel": "CACC & platooning"},
  {"from": "r42", "to": "r43", "rel": "Rail grade crossings"},
  {"from": "r12", "to": "r13", "rel": "Extreme weather"},
  {"from": "r12", "to": "r21", "rel": "Extreme weather"},
  {"from": "r13", "to": "r21", "rel": "Extreme weather"},
  {"from": "r14", "to": "r15", "rel": "goMARTI pilot"}
];
