var EDGES = [
  {"from": "r1", "to": "r18", "rel": "Single-sensor limits"},
  {"from": "r1", "to": "r20", "rel": "Single-sensor limits"},
  {"from": "r18", "to": "r20", "rel": "Single-sensor limits"},
  {"from": "r2", "to": "r17", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r18", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r2", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r18", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r17", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r18", "to": "r19", "rel": "Multi-sensor fusion"},
  {"from": "r19", "to": "r20", "rel": "Multi-sensor fusion"},
  {"from": "r3", "to": "r21", "rel": "Adverse-weather perception"},
  {"from": "r3", "to": "r22", "rel": "Adverse-weather perception"},
  {"from": "r21", "to": "r22", "rel": "Adverse-weather perception"},
  {"from": "r1", "to": "r2", "rel": "GNSS/LiDAR failure modes"},
  {"from": "r2", "to": "r23", "rel": "HD-map localization"},
  {"from": "r2", "to": "r24", "rel": "HD-map localization"},
  {"from": "r2", "to": "r25", "rel": "HD-map localization"},
  {"from": "r23", "to": "r24", "rel": "HD-map localization"},
  {"from": "r23", "to": "r25", "rel": "HD-map localization"},
  {"from": "r24", "to": "r25", "rel": "HD-map localization"},
  {"from": "r1", "to": "r4", "rel": "Energy & terrain routing"},
  {"from": "r1", "to": "r26", "rel": "Energy & terrain routing"},
  {"from": "r1", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r4", "to": "r26", "rel": "Energy & terrain routing"},
  {"from": "r4", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r26", "to": "r27", "rel": "Energy & terrain routing"},
  {"from": "r5", "to": "r16", "rel": "On-demand vs fixed routing"},
  {"from": "r5", "to": "r30", "rel": "On-demand vs fixed routing"},
  {"from": "r5", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r16", "to": "r30", "rel": "On-demand vs fixed routing"},
  {"from": "r16", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r30", "to": "r31", "rel": "On-demand vs fixed routing"},
  {"from": "r19", "to": "r25", "rel": "Heterogeneous data fusion"},
  {"from": "r5", "to": "r28", "rel": "On-demand dispatch"},
  {"from": "r5", "to": "r29", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r29", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r30", "rel": "On-demand dispatch"},
  {"from": "r28", "to": "r31", "rel": "On-demand dispatch"},
  {"from": "r29", "to": "r30", "rel": "On-demand dispatch"},
  {"from": "r29", "to": "r31", "rel": "On-demand dispatch"},
  {"from": "r7", "to": "r37", "rel": "Digital twins"},
  {"from": "r7", "to": "r38", "rel": "Digital twins"},
  {"from": "r7", "to": "r25", "rel": "Digital infrastructure"},
  {"from": "r25", "to": "r37", "rel": "Digital infrastructure"},
  {"from": "r25", "to": "r38", "rel": "Digital infrastructure"},
  {"from": "r37", "to": "r38", "rel": "Digital twins"},
  {"from": "r39", "to": "r46", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r47", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r48", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r49", "rel": "Physical road assessment"},
  {"from": "r46", "to": "r47", "rel": "Physical road assessment"},
  {"from": "r46", "to": "r48", "rel": "Physical road assessment"},
  {"from": "r46", "to": "r49", "rel": "Physical road assessment"},
  {"from": "r47", "to": "r48", "rel": "Physical road assessment"},
  {"from": "r47", "to": "r49", "rel": "Physical road assessment"},
  {"from": "r48", "to": "r49", "rel": "Physical road assessment"},
  {"from": "r9", "to": "r50", "rel": "Rural V2X"},
  {"from": "r9", "to": "r51", "rel": "Rural V2X"},
  {"from": "r9", "to": "r52", "rel": "Rural V2X"},
  {"from": "r50", "to": "r51", "rel": "Rural V2X"},
  {"from": "r50", "to": "r52", "rel": "Rural V2X"},
  {"from": "r51", "to": "r52", "rel": "Rural V2X"},
  {"from": "r44", "to": "r45", "rel": "V2X cybersecurity"},
  {"from": "r10", "to": "r35", "rel": "Cooperative perception"},
  {"from": "r34", "to": "r36", "rel": "Edge RSU handover"},
  {"from": "r40", "to": "r41", "rel": "CACC & platooning"},
  {"from": "r42", "to": "r43", "rel": "Rail grade crossings"},
  {"from": "r12", "to": "r13", "rel": "Extreme weather"},
  {"from": "r12", "to": "r21", "rel": "Extreme weather"},
  {"from": "r13", "to": "r21", "rel": "Extreme weather"},
  {"from": "r14", "to": "r15", "rel": "goMARTI pilot"},
  {"from": "r14", "to": "r16", "rel": "Remote supervision and fleet management"},
  {"from": "r15", "to": "r16", "rel": "Remote supervision and fleet management"},
  {"from": "r2", "to": "r56", "rel": "Perception - multi-sensor fusion"},
  {"from": "r2", "to": "r56", "rel": "Data integration - heterogeneous & aggregated"},
  {"from": "r2", "to": "r57", "rel": "Perception - multi-sensor fusion"},
  {"from": "r17", "to": "r57", "rel": "Data integration - onboard raw & semantic"},
  {"from": "r2", "to": "r58", "rel": "Perception - multi-sensor fusion"},
  {"from": "r3", "to": "r58", "rel": "Perception - adverse weather"},
  {"from": "r2", "to": "r59", "rel": "Perception - multi-sensor fusion"},
  {"from": "r2", "to": "r59", "rel": "Data integration - heterogeneous & aggregated"},
  {"from": "r2", "to": "r60", "rel": "Localization - fusion with HD maps"},
  {"from": "r1", "to": "r61", "rel": "Localization - GNSS/LiDAR limits"},
  {"from": "r3", "to": "r61", "rel": "Perception - adverse weather"},
  {"from": "r1", "to": "r62", "rel": "Localization - GNSS/LiDAR limits"},
  {"from": "r2", "to": "r63", "rel": "Perception - multi-sensor fusion"},
  {"from": "r17", "to": "r63", "rel": "Data integration - onboard raw & semantic"},
  {"from": "r1", "to": "r64", "rel": "Perception - single sensor"},
  {"from": "r2", "to": "r64", "rel": "Perception - multi-sensor fusion"},
  {"from": "r4", "to": "r65", "rel": "Routing - energy & terrain aware"},
  {"from": "r4", "to": "r66", "rel": "Routing - energy & terrain aware"},
  {"from": "r4", "to": "r67", "rel": "Routing - energy & terrain aware"},
  {"from": "r5", "to": "r68", "rel": "On-demand dispatch & ride-matching"},
  {"from": "r16", "to": "r69", "rel": "Fixed-route dispatch & scheduling"},
  {"from": "r5", "to": "r69", "rel": "Routing - on-demand vs fixed route"},
  {"from": "r5", "to": "r70", "rel": "On-demand dispatch & ride-matching"},
  {"from": "r5", "to": "r71", "rel": "On-demand dispatch & ride-matching"},
  {"from": "r14", "to": "r72", "rel": "Fleet support - charging, monitoring & fares"},
  {"from": "r5", "to": "r73", "rel": "On-demand dispatch & ride-matching"},
  {"from": "r14", "to": "r74", "rel": "Fleet support - charging, monitoring & fares"},
  {"from": "r5", "to": "r75", "rel": "On-demand dispatch & ride-matching"},
  {"from": "r14", "to": "r75", "rel": "Fleet support - charging, monitoring & fares"},
  {"from": "r14", "to": "r76", "rel": "Fleet support - charging, monitoring & fares"},
  {"from": "r16", "to": "r77", "rel": "Fixed-route dispatch & scheduling"},
  {"from": "r14", "to": "r77", "rel": "Fleet support - charging, monitoring & fares"},
  {"from": "r16", "to": "r78", "rel": "Fixed-route dispatch & scheduling"},
  {"from": "r5", "to": "r78", "rel": "Routing - on-demand vs fixed route"},
  {"from": "r16", "to": "r79", "rel": "Remote monitoring & supervision"},
  {"from": "r39", "to": "r80", "rel": "Physical road assessment"},
  {"from": "r7", "to": "r80", "rel": "Digital road-information layer"},
  {"from": "r39", "to": "r81", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r82", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r83", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r84", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r85", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r86", "rel": "Physical road assessment"},
  {"from": "r39", "to": "r87", "rel": "Physical road assessment"},
  {"from": "r7", "to": "r87", "rel": "Digital road-information layer"},
  {"from": "r39", "to": "r88", "rel": "Physical road assessment"},
  {"from": "r7", "to": "r89", "rel": "Digital road-information layer"},
  {"from": "r7", "to": "r90", "rel": "Digital road-information layer"},
  {"from": "r7", "to": "r91", "rel": "Digital road-information layer"},
  {"from": "r9", "to": "r92", "rel": "Rural V2X"},
  {"from": "r8", "to": "r92", "rel": "Multi-channel connectivity"},
  {"from": "r9", "to": "r93", "rel": "Rural V2X"},
  {"from": "r8", "to": "r93", "rel": "Multi-channel connectivity"},
  {"from": "r8", "to": "r94", "rel": "Multi-channel connectivity"},
  {"from": "r9", "to": "r95", "rel": "Rural V2X"},
  {"from": "r9", "to": "r96", "rel": "Rural V2X"},
  {"from": "r9", "to": "r97", "rel": "Rural V2X"},
  {"from": "r9", "to": "r98", "rel": "Rural V2X"},
  {"from": "r44", "to": "r99", "rel": "V2X cybersecurity"},
  {"from": "r44", "to": "r100", "rel": "V2X cybersecurity"},
  {"from": "r44", "to": "r101", "rel": "V2X cybersecurity"},
  {"from": "r44", "to": "r102", "rel": "V2X cybersecurity"},
  {"from": "r9", "to": "r103", "rel": "Rural V2X"},
  {"from": "r8", "to": "r103", "rel": "Multi-channel connectivity"},
  {"from": "r10", "to": "r104", "rel": "Cooperative perception"},
  {"from": "r10", "to": "r105", "rel": "Cooperative perception"},
  {"from": "r10", "to": "r106", "rel": "Cooperative perception"},
  {"from": "r34", "to": "r107", "rel": "Infrastructure-assisted control & handover"},
  {"from": "r10", "to": "r108", "rel": "Cooperative perception"},
  {"from": "r34", "to": "r108", "rel": "Infrastructure-assisted control & handover"},
  {"from": "r10", "to": "r109", "rel": "Cooperative perception"},
  {"from": "r40", "to": "r110", "rel": "CACC & platooning"},
  {"from": "r40", "to": "r111", "rel": "CACC & platooning"},
  {"from": "r40", "to": "r112", "rel": "CACC & platooning"},
  {"from": "r11", "to": "r113", "rel": "Work & school zones"},
  {"from": "r34", "to": "r114", "rel": "Infrastructure-assisted control & handover"},
  {"from": "r11", "to": "r115", "rel": "Work & school zones"},
  {"from": "r34", "to": "r115", "rel": "Infrastructure-assisted control & handover"},
  {"from": "r16", "to": "r116", "rel": "Public-lands fixed-route pilots"},
  {"from": "r16", "to": "r117", "rel": "Public-lands fixed-route pilots"}
];
