const chapters=[
{name:'The mission',time:'0:00–1:00',label:'01 / RESEARCH QUESTION',title:'Rural mobility needs',intro:'What would it take for an autonomous service to connect rural residents with everyday destinations?',details:[['The research question','Connect everyday mobility needs with the capabilities and evidence required to serve them.']]},
{name:'The constraints',time:'1:00–3:00',label:'02 / RURAL CONSTRAINTS',title:'Rural operating conditions',intro:'Sparse markings, intermittent connectivity, and dispersed demand change the design problem.',details:[['Perception & positioning','The vehicle needs to work with limited road guidance.'],['Connectivity & service','The operator needs a plan when a trip is interrupted.']]},
{name:'The framework',time:'3:00–5:00',label:'03 / THE TWO-TIER FRAMEWORK',title:'The two-tier framework',intro:'The vehicle and service form the baseline. Infrastructure and connectivity extend it where they address a measured need.',details:[['Tier 1 / Drive + operate','Autonomous Driving and Fleet Management'],['Tier 2 / Road + connect + cooperate','Infrastructure, Communication and Cooperative Driving']]},
{name:'The evidence',time:'5:00–7:00',label:'04 / WHAT THE EVIDENCE CAN SUPPORT',title:'How much evidence is directly rural?',intro:'The corpus supports plausible design directions more strongly than broad rural deployment readiness.',details:[['Each point is a real source record','Select a point to inspect its title, coding and original source.'],['Relevance is not study design','Direct rural evidence includes several kinds of studies.']]},
{name:'The pilots',time:'7:00–9:00',label:'05 / FIELD EXPERIENCE',title:'What the field pilots show',intro:'Four named programs provide bounded operating precedents. They do not establish one universal rural service model.',details:[['Demand-responsive or fixed route','Match the service to the trip pattern and operating context.'],['A clear boundary','Reviewed operations are supervised and geographically bounded.']]},
{name:'The next study',time:'9:00–10:00',label:'06 / BACK TO THE ROUTE',title:'A staged validation plan',intro:'A staged rural pilot can turn the review’s design logic into testable research.',details:[['The contribution','A traceable connection between rural needs, technologies and operating evidence.']]}
];
let current=Math.max(0,Math.min(5,(Number(location.hash.slice(1))||1)-1)),lost=false,tier2=false,focused=false,pilot=0,gate=0;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route='M80 410 L190 410 Q225 410 225 375 L225 320 Q225 275 275 275 L360 275 Q415 275 415 220 L415 170 Q415 115 470 115 L565 115';
function showDialog(html){$('#sourceContent').innerHTML=html;$('#sourceDialog').showModal()}
function paper(n){const p=PAPERS.find(p=>p.n===n);if(!p)return;const url=p.doi?'https://doi.org/'+p.doi:p.arxiv?'https://arxiv.org/abs/'+p.arxiv:p.url;showDialog(`<span class="tag">REFERENCE ${p.n} / ${esc(p.rural)}</span><h2>${esc(p.title)}</h2><p>${esc(p.authors)} · ${p.year}</p><p>${esc(p.venue)}</p><p><strong>${esc(p.cat)}</strong><br>${esc(p.etype)} · Evidence strength: ${esc(p.strength)}</p><p>${esc(p.rav)}</p><a class="source-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open original source ↗</a><p><small>Labels reflect the review team’s coding. They are not formal risk-of-bias or deployment-readiness scores.</small></p>`)}
function sources(ns){showDialog(`<span class="tag">SUPPORTING SOURCES</span><h2>Inspect the evidence</h2>${ns.map(n=>{let p=PAPERS.find(p=>p.n===n);return `<p><button data-paper="${n}">[${n}] ${esc(p.title)} (${p.year})</button></p>`}).join('')}`)}
function map(){return `<div class="map-title">ILLUSTRATIVE SERVICE ROUTE</div><svg viewBox="0 0 650 530" role="img" aria-label="Schematic route from a rural resident to a clinic, with road-marking and connectivity constraints"><defs><pattern id="grid" width="34" height="34" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#263448"/></pattern></defs><path d="M25 200H180M325 450H620M100 70V200M535 300V500" stroke="#e8e8e8" stroke-width="2" fill="none"/><path class="route-base" d="${route}"/><path class="${current?'route-active':'route-line'}" d="${route}"/><circle cx="80" cy="410" r="9" fill="#333"/><circle cx="565" cy="115" r="9" fill="#333"/><text x="42" y="465" class="map-label">Resident</text><text x="519" y="72" class="map-label">Clinic</text><g class="vehicle" transform="translate(${current?lost?'280 275':'350 275':'115 410'})"><circle r="17" fill="#fff" stroke="${lost?'#a78d58':'#315b78'}" stroke-width="3"/><path d="M-5 -5L6 0 -5 5" fill="none" stroke="#333" stroke-width="2"/></g>${current?`<g class="hazard" tabindex="0" role="button" aria-label="Sparse road markings evidence" data-hazard="markings" transform="translate(225 350)"><circle r="18" fill="#a51c30"/><text y="6" text-anchor="middle" fill="#fff" font-size="19">!</text></g><text x="15" y="329" class="map-label">Sparse markings</text><g class="hazard" tabindex="0" role="button" aria-label="Connectivity gap evidence" data-hazard="signal" transform="translate(415 200)"><circle r="18" fill="#a78d58"/><text y="6" text-anchor="middle" fill="#fff" font-size="19">!</text></g><text x="457" y="211" class="map-label">Coverage gap</text>`:''}</svg><div class="state">${current?(lost?'Connection lost · A tested fallback is required':'Connection available · External support can assist'):'The mission is a complete passenger journey.'}</div><div class="caption">Illustrative schematic. No real route, distance, or vehicle performance is implied.</div>`}
function framework(){return `<div class="map-title">CAPABILITIES AND VALIDATION</div><svg viewBox="0 0 650 520" role="img" aria-label="Tier one vehicle and fleet, tier two infrastructure communication and cooperation, with field validation"><text x="35" y="70" class="map-small">TIER 1 / OPERATING BASELINE</text><rect class="module-box" x="35" y="90" width="275" height="110" rx="8"/><rect class="module-box" x="330" y="90" width="285" height="110" rx="8"/><text x="55" y="125" class="module-label">Autonomous Driving</text><text x="55" y="163" class="map-small">Sensing · positioning · fallback</text><text x="350" y="125" class="module-label">Fleet Management</text><text x="350" y="163" class="map-small">Dispatch · charging · supervision</text><g id="tierSupport" opacity="${tier2?1:.15}" style="transition:opacity .5s"><path d="M170 200V250M470 200V250" stroke="#315b78" stroke-width="2"/><text x="35" y="240" class="map-small">TIER 2 / SELECTIVE SUPPORT</text>${['Infrastructure','Communication','Cooperative Driving'].map((t,i)=>`<rect class="module-box t2" x="${35+i*198}" y="260" width="184" height="90" rx="8"/><text x="${47+i*198}" y="310" class="module-label" style="font-size:15px">${t}</text>`).join('')}</g><path d="M325 355V400" stroke="#a51c30" stroke-width="2"/><text x="325" y="438" text-anchor="middle" fill="#a51c30" font-size="24">Field pilots validate the limits</text><text x="325" y="474" text-anchor="middle" class="map-small">Defined conditions before broader operation</text></svg><div class="caption">The tiers organize the review. They are not SAE automation levels.</div>`}
function evidence(){return `<div class="legend"><span><i style="background:var(--red)"></i>12 direct rural</span><span><i style="background:#c3c8cd"></i>99 transferable</span><span><i style="background:var(--gold)"></i>7 context-limited</span></div><div class="point-area ${focused?'focus':''}">${PAPERS.map(p=>`<button class="point ${p.rural==='Direct rural evidence'?'direct':p.rural==='Context-limited'?'context':''}" data-paper="${p.n}" aria-label="Reference ${p.n}: ${esc(p.title)}. ${esc(p.rural)}" title="[${p.n}] ${esc(p.title)}"></button>`).join('')}</div><div class="evidence-stat"><b>10.2%</b><span>direct rural relevance<br>12 / 118 source records</span></div>`}
const pilots=[['goMARTI','Grand Rapids, Minnesota','On-demand','Flexible booking and accessible support for dispersed riders. The reviewed operation is low-speed and geofenced with an onboard safety operator.',[14,15]],['ADASTEC','Sleeping Bear Dunes, Michigan','Fixed route','A defined route supports a scheduled service, with supervised operation and energy and interruption planning.',[16]],['TEDDY','Yellowstone National Park','Fixed route','Remote park service connects weather, communication and service interruptions within a bounded operating setting.',[116]],['CASSI','Wright Brothers + North Carolina sites','Fixed route','Multiple public sites provide operating experience. Comparable reporting helps identify recurring barriers.',[116,117]]];
function photoView(i){const p=PHOTOS[i];return `<figure class="field-photo"><div class="photo-window"><img class="photo-shot" src="${esc(p.src)}" alt="${esc(p.alt)}" decoding="async" referrerpolicy="no-referrer"></div><figcaption><span>PROJECT PHOTOGRAPH</span><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.credit)} ↗</a></figcaption></figure>`;}
function mission(){
 if(beat===0)return `<div class="project-mission"><div class="project-kicker">TRAVELS / THE MOBILITY QUESTION</div><figure class="demo-context"><div class="demo-scene"><img src="assets/travels-sensing-poster.jpg" alt="Front road-camera view from the team's small demonstration, with road markings, traffic and trees"></div><figcaption>From a small team demonstration, shown here to illustrate the driving environment.</figcaption></figure><div class="mission-purpose">A dependable journey<br><em>to everyday destinations.</em></div><div class="mission-credit">Team demo image · TRAVELS Intro, slide 10</div></div>`;
 if(beat===1)return `<div class="project-mission"><div class="project-kicker">TRAVELS / SENSING EXAMPLE</div><figure class="sensing-figure"><video id="project-video" controls muted playsinline preload="none" poster="assets/travels-sensing-poster.jpg" aria-label="Twelve-second camera and LiDAR recording from the TRAVELS introduction"><source src="assets/travels-sensing-12s.mp4" type="video/mp4">Your browser does not support this video. <a href="assets/travels-sensing-12s.mp4">Open the recording</a>.</video><button id="clip-play" class="clip-play">Play 12-second clip</button><figcaption><span>CAMERAS + LIDAR</span><span>12-second excerpt · silent</span></figcaption></figure><div class="sensing-readout"><p><strong>Observe the road</strong><span>Camera views show markings, signals and traffic.</span></p><p><strong>Recover geometry</strong><span>LiDAR adds the spatial structure around the vehicle.</span></p></div><div class="caption">Camera and LiDAR views from the team’s small demo · TRAVELS Intro, slide 10.</div></div>`;
 return `<div class="project-mission review-bridge"><div class="project-kicker">THE ROLE OF THIS REVIEW</div><div class="bridge-question">Which capabilities<br>can support<br><em>rural mobility?</em></div><div class="bridge-rows"><div><span>01</span><strong>Rural operating needs</strong><small>Access, road conditions and service continuity</small></div><div><span>02</span><strong>Research evidence</strong><small>118 sources across five technical modules and pilots</small></div><div><span>03</span><strong>Conditions for testing</strong><small>Transfer assumptions, limitations and validation measures</small></div></div><div class="opening-credit">Que · Zhu · Yao<br>College of Engineering, University of Georgia</div></div>`;
}
function pilotView(){const p=pilots[pilot];return `<div class="pilot-gallery"><div class="pilot-tabs" aria-label="Select a field pilot">${pilots.map((p,i)=>`<button data-pilot="${i}" aria-pressed="${i===pilot}"><span>0${i+1}</span>${p[0]}</button>`).join('')}</div>${photoView(pilot)}<div class="pilot-heading"><div><h2>${p[0]}</h2><p>${p[1]}</p></div><span class="service-type">${p[2]}</span></div><div class="pilot-details">${p[3]} <button class="secondary" id="pilotSources">Sources ↗</button></div></div>`;}
function nextStudy(){return `<div class="timeline">${[['Define the operating domain','Roads, speed, weather and service conditions'],['Test the baseline','Onboard capability and safe fallback'],['Address a measured gap','Targeted road or communication support'],['Review before expansion','Comparable safety and service outcomes']].map((x,i)=>`<div class="step ${i<=gate?'active':''}"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}<div class="measure"><b>MEASURE</b><br>Interventions · disconnections · energy<br>Accessibility · rider outcomes · operator workload</div></div><div class="caption">Proposed sequence synthesized across studies. It still requires rural validation.</div>`}
function render(){const c=chapters[current];$('#eyebrow').textContent=c.label;$('#title').innerHTML=c.title;$('#intro').textContent=c.intro;$('#details').innerHTML=c.details.map(x=>`<div class="detail"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('#visual').className='visual '+(lost&&current===1?'signal-loss':'');$('#visual').innerHTML=[mission,map,framework,evidence,pilotView,nextStudy][current]();$('#actions').innerHTML=current===0?'<button class="action" id="begin">Examine the constraints</button>':current===1?`<button class="action" id="signal">${lost?'Restore connection':'Simulate connection loss'}</button><button class="secondary" id="constraintSources">Supporting sources</button>`:current===2?`<button class="action" id="tiers">${tier2?'Show baseline only':'Add selective support'}</button><button class="secondary" id="frameworkSources">Supporting sources</button>`:current===3?`<button class="action" id="focus">${focused?'Show all evidence':'Highlight direct rural evidence'}</button>`:current===5?`<button class="action" id="gate">${gate<3?'Reveal next step':'Return to the mission'}</button><button class="secondary" id="review">Open the review ↗</button>`:'';$('#number').textContent=String(current+1).padStart(2,'0');$('#chapterName').textContent=c.name;$('#time').textContent=c.time;$('#prev').disabled=current===0;$('#next').disabled=current===5;$('#chapters').innerHTML=chapters.map((c,i)=>`<button aria-label="Chapter ${i+1}: ${c.name}" aria-current="${i===current}" data-chapter="${i}" title="${c.name}"></button>`).join('');$('#announcement').textContent=`Chapter ${current+1}: ${c.name}`;}
function go(n){n=Math.max(0,Math.min(5,n));if(n===current)return;current=n;beat=0;applyBeat();history.replaceState(null,'','#'+(current+1));render();$('#stage').classList.remove('enter');void $('#stage').offsetWidth;$('#stage').classList.add('enter')}
document.addEventListener('click',e=>{const t=e.target.closest('button,[data-hazard]');if(!t)return;if(t.dataset.chapter!==undefined)return go(+t.dataset.chapter);if(t.dataset.paper)return paper(+t.dataset.paper);if(t.dataset.pilot!==undefined){pilot=+t.dataset.pilot;beat=pilot===0?0:1;return render()}if(t.dataset.hazard)return sources(t.dataset.hazard==='markings'?[1,2,3]:[9,50,92]);switch(t.id){case 'clip-play':{const video=$('#project-video');if(video.paused)video.play().catch(()=>{$('#announcement').textContent='Video unavailable. Try the player controls.'});else video.pause();break;}case 'begin':case 'next':advance(1);break;case 'prev':advance(-1);break;case 'fullButton':if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{$('#announcement').textContent='Fullscreen unavailable. Use your browser fullscreen command.'});break;case 'signal':beat=lost?0:1;applyBeat();render();$('#signal').focus();break;case 'tiers':beat=tier2?0:1;applyBeat();render();$('#tiers').focus();break;case 'focus':beat=focused?0:1;applyBeat();render();$('#focus').focus();break;case 'constraintSources':sources([1,9,50]);break;case 'frameworkSources':sources([1,7,9,14,116]);break;case 'pilotSources':sources(pilots[pilot][4]);break;case 'gate':if(gate<3){advance(1);$('#gate').focus()}else go(0);break;case 'review':window.open('https://uga-mobility-lab.github.io/rav-literature-review/','_blank','noopener,noreferrer');break;}if(t.classList.contains('close'))$('#sourceDialog').close()});
document.addEventListener('keydown',e=>{if($('#sourceDialog').open||e.target.closest('video,audio,textarea,select'))return;if(e.target.closest('[data-hazard]')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.closest('[data-hazard]').dispatchEvent(new MouseEvent('click',{bubbles:true}));return}if(e.key.toLowerCase()==='f'){$('#fullButton').click();return}if(e.target.closest('button,a,input'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();advance(1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();advance(-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(5)}});
window.addEventListener('hashchange',()=>{current=Math.max(0,Math.min(5,(Number(location.hash.slice(1))||1)-1));beat=0;applyBeat();render()});
$('#sourceDialog').addEventListener('click',e=>{if(e.target===$('#sourceDialog'))$('#sourceDialog').close()});
if(new URLSearchParams(location.search).has('embedded'))document.body.classList.add('embedded');
let beat=0;
function applyBeat(){lost=current===1&&beat===1;tier2=current===2&&beat>0;focused=current===3&&beat>0;if(current===4)pilot=beat===0?0:beat===1?1:3;if(current===5)gate=beat===0?1:beat===1?2:3;}
function advance(delta){if(delta>0){if(beat<2)beat++;else if(current<5){current++;beat=0;}else return;}else{if(beat>0)beat--;else if(current>0){current--;beat=2;}else return;}applyBeat();history.replaceState(null,'','#'+(current+1));render();$('#stage').classList.remove('enter');void $('#stage').offsetWidth;$('#stage').classList.add('enter');}
function renderBeat(){const b=BEATS[current][beat];$('#intro').textContent=b[1];let lead=$('#beatLead');if(!lead){lead=document.createElement('div');lead.id='beatLead';$('#intro').before(lead);}lead.textContent=b[0];$('#eyebrow').textContent=chapters[current].label+' · STEP '+(beat+1)+' / 3';$('#prev').disabled=current===0&&beat===0;$('#next').disabled=current===5&&beat===2;$('#time').textContent=chapters[current].time;const begin=$('#begin');if(begin)begin.textContent=beat<2?'Continue':'Examine the constraints';const info={type:'rav-chapter',chapter:current,step:beat,name:chapters[current].name,target:current===4?'pilot:'+pilot:current===2&&beat<2?'tier:'+beat:b[2]};if(parent!==window){if(parent.RAVSync)parent.RAVSync(info);else parent.postMessage(info,location.origin);}}
applyBeat();
const originalRender=render;
render=function(){originalRender();renderBeat();};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='rav-control')return;if(e.data.action==='next')advance(1);if(e.data.action==='previous')advance(-1);});
render();


window.RAVPresentation={next:()=>advance(1),previous:()=>advance(-1)};

document.addEventListener("error",e=>{if(e.target.matches?.(".photo-shot")){e.target.hidden=true;e.target.parentElement.classList.add("photo-unavailable");e.target.parentElement.textContent="Photo unavailable — open the credited source below.";}},true);

for(const event of ['play','pause','ended'])document.addEventListener(event,e=>{if(e.target.id==='project-video'&&$('#clip-play'))$('#clip-play').textContent=e.target.paused?'Play 12-second clip':'Pause clip';},true);
