// Audience-facing explanations of the review's actual methods and evidence.
// Source content: index.html #methodology / #findings and app.js RAV_THEMES.
function reviewMethod(){
  const count=PAPERS.length;
  const years=PAPERS.map(p=>Number(p.year)).filter(Number.isFinite);
  if(beat===0)return `<div class="review-story"><div class="story-kicker">REVIEW BOUNDARY</div><div class="story-statement">What belongs<br>in the evidence base?</div><div class="story-rows"><div><span>Period</span><p>${Math.min(...years)}–${Math.max(...years)}</p></div><div><span>Coverage</span><p>Five technical modules, with field pilots as an operational validation layer.</p></div><div><span>Relevance</span><p>Automated road transport with direct rural evidence or a documented path to rural use.</p></div></div><p class="story-footnote">The review records the transfer assumption when a study comes from another operating setting.</p></div>`;
  if(beat===1)return `<div class="review-story"><div class="story-kicker">SEARCH → SCREEN → RETAIN</div><div class="story-method-flow"><div><span class="story-number">01</span><div><h2>Search across source types</h2><p>Scholarly records, authoritative reports and official pilot pages; follow reference chains across studies.</p></div></div><div><span class="story-number">02</span><div><h2>Apply the relevance rule</h2><p>Keep direct rural work and documented transfer paths. Remove duplicates, unverifiable records and unrelated transport modes.</p></div></div><div><span class="story-number">03</span><div><h2>${count} retained records</h2><p>A source collection covering technical methods and operational experience.</p></div></div></div><p class="story-footnote">Retained-record count. The website does not present a quantitative meta-analysis.</p></div>`;
  const doi=PAPERS.filter(p=>p.doi).length;
  const arxiv=PAPERS.filter(p=>!p.doi&&p.arxiv).length;
  const pages=count-doi-arxiv;
  return `<div class="review-story"><div class="story-kicker">VERIFIABLE SOURCES · EXPLICIT CODING</div><div class="story-metrics" aria-label="Source verification routes"><div><strong>${doi}</strong><span>DOI records</span></div><div><strong>${arxiv}</strong><span>arXiv records</span></div><div><strong>${pages}</strong><span>authoritative pages</span></div></div><div class="story-rows"><div><span>What it studies</span><p>Module · study design · publication year</p></div><div><span>How it transfers</span><p>Rural relevance · evidence strength</p></div><div><span>How to inspect it</span><p>Original source · access status · verification audit</p></div></div><p class="story-footnote">Strength and rural relevance are separate review-team labels. Strength is not a formal risk-of-bias or readiness score.</p></div>`;
}

function reviewFindings(){
  const findings=[
    {claim:'Keep the core self-reliant.',evidence:'Reviews converge on perception, sensor fusion, localization and mapping as the reusable AV baseline.',implication:'Keep safety-critical sensing, positioning, planning and fallback onboard; test their limits on local roads.',boundary:'Most representative reviews establish a transfer path; shared rural operating proof remains limited.',refs:[1,2,3,19,23,25]},
    {claim:'Connectivity adds support.',evidence:'Rural measurements show spatially variable links. Cooperative-driving studies establish possibilities that still require rural testing.',implication:'Use external links opportunistically and preserve a tested safe mode through disconnections.',boundary:'Continuous connectivity and roadside support cannot be assumed across a rural service area.',refs:[9,40,41,50,92,94,103]},
    {claim:'Match the service to demand.',evidence:'Modeling and pilots describe complementary operating choices: on-demand rides for dispersed requests and fixed routes for predictable circulation.',implication:'Choose dispatch, charging and passenger support around the trip pattern and operating context.',boundary:'Supervised, bounded pilots do not establish one universal rural service model.',refs:[14,15,16,31,78,116,117]}
  ];
  const f=findings[beat];
  return `<div class="review-story"><div class="story-kicker">FINDING ${String(beat+1).padStart(2,'0')} / CROSS-CUTTING SYNTHESIS</div><div class="story-statement">${esc(f.claim)}</div><div class="story-rows"><div><span>Evidence</span><p>${esc(f.evidence)}</p></div><div><span>Implication</span><p>${esc(f.implication)}</p></div></div><p class="story-boundary">${esc(f.boundary)}</p><div class="story-citations"><span>Sources</span>${f.refs.map(n=>`<button type="button" data-paper="${n}" aria-label="Inspect reference ${n}">[${n}]</button>`).join('')}</div></div>`;
}

function evidenceTrail(){
  const p=PAPERS.find(p=>p.n===2);
  const source=p?`<button type="button" class="story-source-title" data-paper="2">[2] ${esc(p.title)}</button><p class="story-source-meta">${esc(p.venue)} · ${esc(p.year)}</p><div class="story-source-coding"><span>${esc(p.etype)}</span><span>${esc(p.strength)} strength</span><span>${esc(p.rural)}</span></div>`:'<p>Inspect reference [2] in the review database.</p>';
  return `<div class="review-story evidence-trail"><div class="story-kicker">READ ONE EVIDENCE CHAIN</div><div class="story-trail-row"><span class="story-number">01</span><div><p class="story-trail-label">Theme</p><h2><button class="story-theme-link" data-review-theme="Perception - multi-sensor fusion">Perception — multi-sensor fusion</button></h2><p class="story-direction">Recommended direction · rural validation needed</p></div></div><div class="story-trail-row"><span class="story-number">02</span><div><p class="story-trail-label">One supporting source</p>${source}</div></div><div class="story-trail-row"><span class="story-number">03</span><div><p class="story-trail-label">Follow the validation question</p><h2><button class="story-theme-link" data-review-theme="Perception - adverse weather">Perception — adverse weather</button></h2><p>Fusion needs calibration and local testing. Several sensors can still be affected by the same weather conditions.</p></div></div><p class="story-footnote">Select either theme to inspect its detail in the review. Each source keeps its own study design and rural-relevance label.</p></div>`;
}

function reviewConclusion(){
  const direct=PAPERS.filter(p=>p.rural==='Direct rural evidence').length;
  return `<div class="review-story"><div class="story-kicker">WHAT THIS REVIEW CONTRIBUTES</div><div class="story-statement">A traceable basis<br>for the next study.</div><div class="story-rows"><div><span>Contribution</span><p>Connect rural operating needs, five technical modules and field experience to testable design choices.</p></div><div><span>Evidence boundary</span><p>${direct} of ${PAPERS.length} source records are directly rural. The integrated deployment sequence is the review team’s synthesis.</p></div><div><span>Next measurements</span><p>Interventions · disconnections · energy<br>Accessibility · rider outcomes · operator workload</p></div></div><p class="story-footnote">Use comparable rural operating data to test the sequence before expanding service.</p></div>`;
}
