// Audience-facing explanations of the review's actual methods and evidence.
// Source content: index.html #methodology / #findings and app.js RAV_THEMES.
function reviewMethod(){
  const count=PAPERS.length;
  const years=PAPERS.map(p=>Number(p.year)).filter(Number.isFinite);
  if(beat===0)return `<div class="review-story"><div class="story-kicker">REVIEW BOUNDARY</div><div class="story-statement">What belongs<br>in the evidence base?</div><div class="story-rows"><div><span>Period</span><p>${Math.min(...years)}–${Math.max(...years)}</p></div><div><span>Coverage</span><p>Five technical modules, with field pilots as an operational validation layer.</p></div><div><span>Relevance</span><p>Automated road transport with direct rural evidence or a documented path to rural use.</p></div></div><p class="story-footnote">The review records the transfer assumption when a study comes from another operating setting.</p></div>`;
  if(beat===1)return `<div class="review-story"><div class="story-kicker">SEARCH → SCREEN → RETAIN</div><div class="story-method-flow"><div><span class="story-number">01</span><div><h2>Search across source types</h2><p>Scholarly records, authoritative reports and official pilot pages; follow reference chains across studies.</p></div></div><div><span class="story-number">02</span><div><h2>Apply the relevance rule</h2><p>Keep direct rural work and documented transfer paths. Remove duplicates, unverifiable records and unrelated transport modes.</p></div></div><div><span class="story-number">03</span><div><h2>${count} retained records</h2><p>A source collection covering technical methods and operational experience.</p></div></div></div><p class="story-footnote">Retained-record count. The website does not present a quantitative meta-analysis.</p></div>`;
  const doi=PAPERS.filter(p=>p.doi).length;
  const arxiv=PAPERS.filter(p=>!p.doi&&p.arxiv).length;
  const pages=count-doi-arxiv;
  return `<div class="review-story"><div class="story-kicker">VERIFIABLE SOURCES · EXPLICIT CODING</div><div class="story-metrics" aria-label="Source verification routes"><div><strong>${doi}</strong><span>DOI records</span></div><div><strong>${arxiv}</strong><span>arXiv records</span></div><div><strong>${pages}</strong><span>authoritative pages</span></div></div><div class="story-rows"><div><span>What it studies</span><p>Module · study design · publication year</p></div><div><span>How it transfers</span><p>Rural relevance · evidence strength</p></div><div><span>How to inspect it</span><p>Original source · access status · verification audit</p></div></div><p class="story-footnote">Strength and rural relevance are separate review-team labels. Strength is not a formal risk-of-bias or readiness score.</p></div>`;
}

function reviewFindings(){
  if(beat===0)return `<div class="review-story"><div class="story-kicker">THE SECTION’S CENTRAL ARGUMENT</div><div class="story-statement">Rural conditions shape<br>the system and the service.</div><div class="story-rows"><div><span>Keep the core self-reliant</span><p>Autonomous Driving and Fleet Management carry the service with sparse rural support.</p></div><div><span>Add support selectively</span><p>Infrastructure, communication and cooperation extend the baseline where they address a real need.</p></div><div><span>Validate in stages, then scale</span><p>Bounded field pilots test operating limits and service outcomes before wider operation.</p></div></div><p class="story-footnote">These are the three overview statements at the top of this section. The five findings below explain their evidence and limits.</p></div>`;
  const finding=beat-1;
  if(finding===3)return evidence();
  const findings=[
    {claim:'Keep the core self-reliant.',evidence:'Reviews converge on perception, sensor fusion, localization and mapping as the reusable AV baseline.',implication:'Keep safety-critical sensing, positioning, planning and fallback onboard; test their limits on local roads.',boundary:'Most representative reviews establish a transfer path; shared rural operating proof remains limited.',refs:[1,2,3,19,23,25]},
    {claim:'Connectivity adds support.',evidence:'Rural measurements show spatially variable links. Cooperative-driving studies establish possibilities that still require rural testing.',implication:'Use external links opportunistically and preserve a tested safe mode through disconnections.',boundary:'Continuous connectivity and roadside support cannot be assumed across a rural service area.',refs:[9,40,41,50,92,94,103]},
    {claim:'Match the service to demand.',evidence:'Modeling and pilots describe complementary operating choices: on-demand rides for dispersed requests and fixed routes for predictable circulation.',implication:'Choose dispatch, charging and passenger support around the trip pattern and operating context.',boundary:'Supervised, bounded pilots do not establish one universal rural service model.',refs:[14,15,16,31,78,116,117]}
  ];
  const f=finding===4?{claim:'Expand through measured stages.',evidence:'Across technical studies, infrastructure research and pilot reports, the review connects local screening, onboard fallback, selective support and bounded field trials.',implication:'Review comparable safety and service measurements before expanding the operating domain.',boundary:'This integrated sequence is the review team’s synthesis. No single study establishes the whole sequence.',refs:[1,7,9,14,15,50,88,116,117,118]}:findings[finding];
  return `<div class="review-story"><div class="story-kicker">FINDING ${String(finding+1).padStart(2,'0')} / CROSS-CUTTING SYNTHESIS</div><div class="story-statement">${esc(f.claim)}</div><div class="story-rows"><div><span>Evidence</span><p>${esc(f.evidence)}</p></div><div><span>Implication</span><p>${esc(f.implication)}</p></div></div><p class="story-boundary">${esc(f.boundary)}</p><div class="story-citations"><span>Sources</span>${f.refs.map(n=>`<button type="button" data-paper="${n}" aria-label="Inspect reference ${n}">[${n}]</button>`).join('')}</div></div>`;
}

function storyCitations(numbers,label='Sources'){
  return `<div class="story-citations"><span>${esc(label)}</span>${numbers.map(n=>`<button type="button" data-paper="${n}" aria-label="Inspect reference ${n}">[${n}]</button>`).join('')}</div>`;
}

function storySourceRecord(n){
  const p=PAPERS.find(p=>p.n===n);
  if(!p)return `<p>Inspect reference [${n}] in the review database.</p>`;
  return `<button type="button" class="story-source-title" data-paper="${n}">[${n}] ${esc(p.title)}</button><p class="story-source-meta">${esc(p.venue)} · ${esc(p.year)}</p><div class="story-source-coding"><span>${esc(p.etype)}</span><span>${esc(p.strength)} strength</span><span>${esc(p.rural)}</span></div>`;
}

function evidenceMapView(){
  if(beat===0)return `<div class="review-story"><div class="story-kicker">HOW TO READ THE EVIDENCE MAP</div><div class="story-statement">25 themes.<br>Three evidence roles.</div><div class="story-rows"><div><span>Limitation</span><p>A failure mode or constraint that motivates a research direction.</p></div><div><span>Recommended direction</span><p>An approach to investigate, with its remaining costs and validation needs.</p></div><div><span>Reusable baseline</span><p>An established capability that can inform rural adaptation.</p></div></div><p class="story-footnote">Rows group themes by module. Each theme opens its definition, benefits, limitations, rural implications and numbered sources. Progression links connect related questions; they are not readiness scores.</p></div>`;
  if(beat===1)return evidenceTrail();
  return `<div class="review-story"><div class="story-kicker">FOLLOW THE VALIDATION QUESTION</div><div class="story-statement">How does fusion hold up<br>in adverse weather?</div><div class="story-rows"><div><span>Theme</span><p>Perception — adverse weather</p></div><div><span>Remaining limitation</span><p>Rain, fog, snow or glare can affect several sensor modalities together. Performance may not generalize across combined conditions.</p></div><div><span>Rural implication</span><p>Collect local weather data, test the combined stack and define safe fallback thresholds for the service area.</p></div></div><div class="story-trail-row"><span class="story-number">[3]</span><div><p class="story-trail-label">One supporting survey</p>${storySourceRecord(3)}</div></div><p class="story-footnote">The theme also cites [21], [22], [58] and [61]. This is a validation need identified by the review, not a demonstrated rural operating result.</p>${storyCitations([21,22,58,61],'Other theme sources')}</div>`;
}

function reviewRecommendations(){
  if(beat===0)return `<div class="review-story"><div class="story-kicker">VEHICLE PLATFORM → FLEET OPERATORS</div><div class="story-statement">Carry the trip<br>and the service.</div><div class="story-rows"><div><span>Vehicle platform</span><p>Build a resilient onboard core: combine sensing and positioning sources, then validate their limits on local roads and in local weather.</p></div><div><span>Fleet operators</span><p>Match dispatch, charging and passenger support to thin demand. Define supervision and takeover procedures for degraded links.</p></div></div><p class="story-footnote">The first two recommendation cards connect vehicle capability with service continuity.</p>${storyCitations([1,2,25],'Vehicle examples')}${storyCitations([14,31,78],'Fleet examples')}</div>`;
  if(beat===1)return `<div class="review-story"><div class="story-kicker">ROAD AGENCIES → CONNECTIVITY PARTNERS</div><div class="story-statement">Add support where<br>the need is measured.</div><div class="story-rows"><div><span>Road agencies</span><p>Assess road condition first. Prioritize high-risk segments, maintain maps and add roadside sensing at conflict points where it helps.</p></div><div><span>Connectivity partners</span><p>Measure route-level coverage and latency. Combine available links and define switching and fallback thresholds before deployment.</p></div></div><p class="story-footnote">The next two cards assign infrastructure and communication tasks while retaining safety-critical capability onboard.</p>${storyCitations([7,88,118],'Road examples')}${storyCitations([9,50,92],'Connectivity examples')}</div>`;
  return `<div class="review-story"><div class="story-kicker">PROGRAM, POLICY AND PILOT PARTNERS</div><div class="story-statement">Make each pilot<br>answer a field question.</div><div class="story-rows"><div><span>Stage the work</span><p>Begin within supervised, bounded operating conditions. Use explicit safety gates before extending the service.</p></div><div><span>Test local challenges</span><p>Include crossings, work and school zones, mixed traffic and adverse-weather fallback.</p></div><div><span>Report comparable measures</span><p>Interventions · disconnections · energy<br>Rider wait time · accessibility · operator workload</p></div></div><p class="story-footnote">The fifth card turns the review’s evidence gaps into questions for program partners and future pilots.</p>${storyCitations([14,15,16,116,117],'Pilot evidence')}</div>`;
}

function reviewReferences(){
  if(beat===0)return `<div class="review-story"><div class="story-kicker">REFERENCE LIST / TRACE ONE SOURCE</div><div class="story-statement">From a number<br>to the original study.</div><div class="story-trail-row"><span class="story-number">[2]</span><div>${storySourceRecord(2)}</div></div><div class="story-rows"><div><span>Find it</span><p>The list groups all ${PAPERS.length} records by RAV module. Reference [2] is in Autonomous Driving.</p></div><div><span>Inspect it</span><p>Open the title for its study design, rural relevance and evidence-strength coding. The source link leads to the original publication.</p></div></div><p class="story-footnote">A high-strength review can still be coded as transferable to rural. These labels describe different aspects of the evidence.</p></div>`;
  const citation=typeof WEBSITE_CITATION!=='undefined'?WEBSITE_CITATION:null;
  const authors=citation?citation.authors.map(author=>author.family).join(', '):'Que, Zhu, Yao';
  const year=citation?citation.year:2026;
  return `<div class="review-story"><div class="story-kicker">CITATION / THE REVIEW’S CONTRIBUTION</div><div class="story-statement">A traceable basis<br>for the next rural study.</div><div class="story-rows"><div><span>What it connects</span><p>Rural needs → technical capabilities → research sources → field lessons.</p></div><div><span>What remains</span><p>Validate the proposed choices with comparable rural operating data before extending service.</p></div><div><span>How to cite it</span><p>${esc(authors)} (${esc(year)}). Use the website citation on the left; APA, IEEE and Chicago styles and citation-file exports are available.</p></div></div><p class="story-footnote">Cite the interactive website for this synthesis and the original publications for their individual results. The formal narrative review is in preparation.</p></div>`;
}

function evidenceTrail(){
  const p=PAPERS.find(p=>p.n===2);
  const source=p?`<button type="button" class="story-source-title" data-paper="2">[2] ${esc(p.title)}</button><p class="story-source-meta">${esc(p.venue)} · ${esc(p.year)}</p><div class="story-source-coding"><span>${esc(p.etype)}</span><span>${esc(p.strength)} strength</span><span>${esc(p.rural)}</span></div>`:'<p>Inspect reference [2] in the review database.</p>';
  return `<div class="review-story evidence-trail"><div class="story-kicker">READ ONE EVIDENCE CHAIN</div><div class="story-trail-row"><span class="story-number">01</span><div><p class="story-trail-label">Theme</p><h2><button class="story-theme-link" data-review-theme="Perception - multi-sensor fusion">Perception — multi-sensor fusion</button></h2><p class="story-direction">Recommended direction · rural validation needed</p></div></div><div class="story-trail-row"><span class="story-number">02</span><div><p class="story-trail-label">One supporting source</p>${source}</div></div><div class="story-trail-row"><span class="story-number">03</span><div><p class="story-trail-label">Follow the validation question</p><h2><button class="story-theme-link" data-review-theme="Perception - adverse weather">Perception — adverse weather</button></h2><p>Fusion needs calibration and local testing. Several sensors can still be affected by the same weather conditions.</p></div></div><p class="story-footnote">Select either theme to inspect its detail in the review. Each source keeps its own study design and rural-relevance label.</p></div>`;
}

function reviewConclusion(){
  const direct=PAPERS.filter(p=>p.rural==='Direct rural evidence').length;
  return `<div class="review-story"><div class="story-kicker">WHAT THIS REVIEW CONTRIBUTES</div><div class="story-statement">A traceable basis<br>for the next study.</div><div class="story-rows"><div><span>Contribution</span><p>Connect rural operating needs, five technical modules and field experience to testable design choices.</p></div><div><span>Evidence boundary</span><p>${direct} of ${PAPERS.length} source records are directly rural. The integrated deployment sequence is the review team’s synthesis.</p></div><div><span>Next measurements</span><p>Interventions · disconnections · energy<br>Accessibility · rider outcomes · operator workload</p></div></div><p class="story-footnote">Use comparable rural operating data to test the sequence before expanding service.</p></div>`;
}
